name: BPF Test

on:
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "go.mod"
      - "go.sum"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/bpf-test.yml"

permissions: read-all

jobs:
  bpf_tests:
    name: BPF Unit Test
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        shell: nix develop --impure . --command bash -e {0}
    strategy:
      matrix:
        clang_version:
          - "18"
          - "19"
          - "20"
          - "21"
          - "22"

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run BPF tests
        env:
          CLANG_VERSION: ${{ matrix.clang_version }}
        run: |
          git submodule update --init
          sudo -E make ebpf-test || (echo "Run 'make ebpf-test' locally to investigate failures"; exit 1)

